- .travis.yml
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/preprocessor.py
- src/bioconda_recipe_gen/recipe.py
- travis/test.sh
The program now uses the c compiler as standard instead
of the cxx compiler.
> The libdivsufsort can now build #65

- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/cli.py
- src/bioconda_recipe_gen/preprocessor.py
- src/bioconda_recipe_gen/recipe.py
There is now a flag --test-files that can be used to give
a list of test files to include in the recipe
> Resolve #78

- MANIFEST.in
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/preprocessor.py
- src/bioconda_recipe_gen/recipes/build.sh
Seems this should be the only thing that is needed to fix the bug, but this is not tested yet. The PR will help with this since it triggers travis to build this branch.
> Deleted build.sh from git, since this file now gets created at runtime

- src/bioconda_recipe_gen/build.py
- travis/test.sh
Added the lambda package to the travis/test.sh
Ran Black on build.py
> Adding seqan-libary to build when cmake error appears

- src/bioconda_recipe_gen/build.py
- travis/test.sh
> NetReg now passes the sanity check Resolve #83.

- src/bioconda_recipe_gen/bioconda_recipe_gen.py
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/preprocessor.py
- src/bioconda_recipe_gen/recipe.py
- src/bioconda_recipe_gen/utils.py
Refactored some of the code on the way, but mostly just
added the increase in build number before sanity check, and
another name for the folder we copy into bioconda-recipes/recipes
> Resolve #91 and Resolve #90

- src/bioconda_recipe_gen/build.py
- travis/test.sh
Add the packages bison, flex and libxml2 in build
> Newick utils recipe

- src/bioconda_recipe_gen/bioconda_recipe_gen.py
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/buildscript.py
- src/bioconda_recipe_gen/cli.py
- src/bioconda_recipe_gen/filesystem.py
- src/bioconda_recipe_gen/preprocessor.py
- src/bioconda_recipe_gen/recipe.py
- travis/test.sh
Extends with a filesystem class which stores the source code for future look ups.
It also adds the package OpenBlas, since NetReg depends on it.
> Iterative buildscripts

- src/bioconda_recipe_gen/buildscript.py
- src/bioconda_recipe_gen/preprocessor.py
The program now chooses a strategy and based on that
creates pair of recipe and buildscript that mathces
the strategy.
> Refactored preprocessor to use different recipes.

- .travis.yml
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/str_to_pkg.py
Instead of writing a lot of if statements (which doesn't scale that well),
we now use a dict saved in the file str_to_pkg.py.
> Refactored our checks for packages.

- src/bioconda_recipe_gen/bioconda_recipe_gen.py
- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/buildscript.py
- src/bioconda_recipe_gen/cli.py
- src/bioconda_recipe_gen/filesystem.py
- src/bioconda_recipe_gen/preprocessors/from_args.py
- src/bioconda_recipe_gen/preprocessors/from_files.py
- src/bioconda_recipe_gen/recipe.py
- src/bioconda_recipe_gen/utils.py
We are switching from handling path joins with string concatenation, like wild west gunslingers, to use os.path.join(...) like proper sophisticated gents.
> All path concatenation is now done using os.path.join(...)

- src/bioconda_recipe_gen/bioconda_recipe_gen.py
- src/bioconda_recipe_gen/preprocessors/from_files.py
- src/bioconda_recipe_gen/recipe.py
- travis/data/2pg_cartesian/patch
- travis/test.sh
This was done by ensuring that we can handle patch files now.
> 2pg_cartesian now builds.

- src/bioconda_recipe_gen/str_to_pkg.py
> Added new packages to look for

- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/recipe.py
- src/bioconda_recipe_gen/str_to_pkg.py
Copying files before sanity check has been fixed. We where not using
copytree right.
Curl has been added as a package.
> The package Hyphy now pass sanity check

- src/bioconda_recipe_gen/build.py
Before 'choose_version' could end up with no valid versions for
a package (if you use python3 but all packages are for python2).
This created an IndexError.
> Fixed bug.

- src/bioconda_recipe_gen/build.py
Instead of default being the newest version, default is now
no version.
> Changed the functionality of version-interaction.

- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/recipe.py
- src/bioconda_recipe_gen/utils.py
Added a regexp to look for versionConflict error message.
> multiqc now builds

- .travis.yml
- setup.py
- src/bioconda_recipe_gen/bioconda_recipe_gen.py
- src/bioconda_recipe_gen/cli.py
- src/bioconda_recipe_gen/preprocessors/from_files.py
- src/bioconda_recipe_gen/template_generation.py
- travis/test.sh
This pull request removes the bioconda-recipes argument and makes the program provide it by itself.
> Use birgorg/bioconda-recipes

- src/bioconda_recipe_gen/build.py
- src/bioconda_recipe_gen/utils.py
Since we are having problems with mounting volumes when spinning a container inside a container, we are going away from volumes and are using put_archive instead
> Replaced volumes with put_archive

- src/bioconda_recipe_gen/build.py
Fixes http error on Linux when docker create can't find our docker hub repo
> Volume to copy
